### ISSUE TITLE
Makefile pandoc optimizations

### ISSUE THREAD

**Issue by averms** [susam/gitpr#3]
I noticed that you aren't using `-f gfm` in your pandoc opts, even though the README is written in
github-flavored markdown. It might reduce the amount of text wrangling that needs to be done before converting.

**Comment by susam** [comment]
Hi @a-vrma,

Thank you for sharing this suggestion.

I am not sure whether `-f gfm` will provide any significant advantage. Most of the text wrangling in the `Makefile` is not about converting one format to another but instead it is about changing the content itself. The content for the PDF output (via `pdflatex`) is a little different from the content for display on the project's README on GitHub. For example, the heading levels of the headings in the README is different from what we want in the PDF output, the Creative Commons logo size is scaled in the PDF output, and so on. These changes go beyond mere format conversion.

I am closing this issue for now. If you have any specific examples from the document where you think an option like `-f gfm` is going to offer significant benefits, please post a comment or send a pull request.
